# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tmachine <tmachine@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/28 20:27:50 by tmachine          #+#    #+#              #
#    Updated: 2021/05/08 16:53:37 by tmachine         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

HEADER			= -I ./libft.h
NAMES			= ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmove.c ft_memchr.c ft_memcmp.c ft_strlen.c \
					ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_toupper.c ft_tolower.c \
					ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strlcpy.c ft_strlcat.c	ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c \
					ft_substr.c \
					ft_strjoin.c ft_strmapi.c ft_strtrim.c ft_split.c ft_itoa.c \
					ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c
BONUS_NAMES		= 	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c ft_lstlast.c \
			 		ft_lstadd_back.c ft_lstdelone.c ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS			= $(NAMES:.c=.o)
BONUS_OBJS		= $(BONUS_NAMES:.c=.o) 

CC				= gcc
CFLAGS			= -Wall -Wextra -Werror
NAME			= libft.a
.DEFAULT_GOAL	= all


.c.o:
	$(CC) $(CFLAGS) $(HEADER) -c $< -o ${<:.c=.o}

all: $(NAME)

$(NAME): $(OBJS) libft.h Makefile
	ar rc $(NAME) $(OBJS)
	ranlib $(NAME)

bonus:  $(BONUS_OBJS)
	ar rc $(NAME) $(BONUS_OBJS)

clean:
	rm -f $(OBJS) $(BONUS_OBJS)

fclean: clean
	rm -f $(NAME)

re:	fclean all

.PHONY: all clean fclean re bonus